### IMPORTING LIBRARIES AND READING DATA

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('mobile_price_range_data.csv')
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

### CHECKING NULL VALUE

In [3]:
df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

### CHECKING DATA TYPE AND ASSIGNING X AND Y

In [4]:
df.dtypes

battery_power      int64
blue               int64
clock_speed      float64
dual_sim           int64
fc                 int64
four_g             int64
int_memory         int64
m_dep            float64
mobile_wt          int64
n_cores            int64
pc                 int64
px_height          int64
px_width           int64
ram                int64
sc_h               int64
sc_w               int64
talk_time          int64
three_g            int64
touch_screen       int64
wifi               int64
price_range        int64
dtype: object

In [5]:
x=df.drop('price_range',axis=1)
y=df['price_range']
print(x.shape)
print(y.shape)

(2000, 20)
(2000,)


### SPLITTING DATA

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [8]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1400, 20)
(600, 20)
(1400,)
(600,)


### DEFINING EVAL MODEL

In [9]:
def eval_model(y_test,y_pred):
    cm=confusion_matrix(y_test,y_pred) 
    print(cm)
    print(classification_report(y_test,y_pred))

### APPLYING LOGISTIC REGRESSION

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
m1=LogisticRegression(solver='liblinear',max_iter=1000)
m1.fit(x_train,y_train)

LogisticRegression(max_iter=1000, solver='liblinear')

In [12]:
print('Train Score',m1.score(x_train,y_train))
print('Test Score',m1.score(x_test,y_test))

Train Score 0.79
Test Score 0.7766666666666666


In [13]:
y_pred=m1.predict(x_test)
print(y_pred)

[0 2 0 3 1 2 2 0 3 1 0 1 1 3 3 1 3 3 1 0 0 1 2 2 0 2 3 3 2 0 0 0 3 0 2 1 2
 0 3 0 2 3 3 0 2 3 1 1 3 1 3 1 0 0 1 2 1 3 0 0 1 3 3 2 0 0 3 3 2 2 2 1 0 1
 3 0 1 3 2 1 3 2 1 0 1 3 2 3 3 0 3 3 2 1 3 2 2 3 2 1 0 0 1 0 0 3 2 0 2 1 0
 0 3 1 3 1 3 3 0 2 1 3 3 2 3 3 0 3 0 2 3 0 1 3 0 3 1 0 0 2 3 1 3 3 0 0 0 2
 2 2 3 1 1 0 2 3 0 1 0 2 2 3 3 1 1 0 0 2 2 2 3 0 0 0 3 1 2 2 1 0 0 0 0 0 3
 2 0 3 0 0 0 0 1 3 3 1 0 1 2 0 1 2 1 3 3 3 1 2 0 0 0 1 1 1 3 1 1 2 1 1 3 1
 3 0 0 3 0 3 0 0 1 0 1 3 2 1 1 2 3 0 2 3 2 3 0 3 1 3 3 3 2 1 0 3 3 1 3 3 3
 3 3 0 1 2 3 2 3 0 2 3 2 3 2 0 0 2 0 3 3 1 3 2 0 3 1 2 0 0 3 0 1 2 3 3 3 0
 1 0 0 3 3 0 1 1 2 0 3 3 2 3 1 3 3 0 2 1 2 2 0 0 0 3 3 3 1 0 1 0 2 3 2 0 2
 2 2 1 3 0 0 3 1 3 1 0 1 1 2 1 2 3 1 0 0 2 3 0 3 0 0 1 0 1 2 2 2 3 0 3 2 3
 3 3 3 3 1 2 0 3 2 3 3 0 2 3 1 3 3 3 1 0 2 3 0 0 2 3 2 1 2 2 1 3 0 3 1 3 0
 0 1 0 1 0 2 0 1 3 3 1 1 1 3 1 1 3 2 0 0 3 0 1 0 0 1 3 3 0 2 0 1 2 3 3 0 3
 0 2 0 0 3 3 0 2 1 2 3 2 1 0 1 3 1 0 3 1 0 0 3 2 3 2 0 3 2 0 1 2 3 2 2 0 0
 0 2 3 1 0 2 3 1 3 1 2 2 

In [14]:
from sklearn.metrics import confusion_matrix,classification_report

In [15]:
eval_model(y_test,y_pred)

[[145   5   1   0]
 [ 13  94  39   0]
 [  0  35  79  34]
 [  0   0   7 148]]
              precision    recall  f1-score   support

           0       0.92      0.96      0.94       151
           1       0.70      0.64      0.67       146
           2       0.63      0.53      0.58       148
           3       0.81      0.95      0.88       155

    accuracy                           0.78       600
   macro avg       0.76      0.77      0.77       600
weighted avg       0.77      0.78      0.77       600



### APPLYING KNN

In [16]:
 from sklearn.neighbors import KNeighborsClassifier

In [17]:
knn = KNeighborsClassifier(n_neighbors=11)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=11)

In [18]:
print('Train Score',knn.score(x_train,y_train))
print('Test Score',knn.score(x_test,y_test))

Train Score 0.9521428571428572
Test Score 0.9316666666666666


C:\Users\Priyam\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\Users\Priyam\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepd

In [19]:
ypred_knn = knn.predict(x_test)
print(ypred_knn)

[0 2 1 3 1 1 2 0 3 1 0 1 2 3 2 2 3 3 1 0 0 1 1 2 0 1 3 2 2 0 0 0 3 0 1 1 2
 0 3 0 2 3 2 0 3 2 2 1 3 1 3 1 0 0 0 1 1 3 0 0 1 3 3 1 0 0 3 3 1 2 2 2 0 1
 2 0 0 3 2 1 3 2 1 0 1 3 1 3 3 0 3 3 2 1 3 2 2 3 1 1 0 0 1 0 0 3 2 0 1 1 0
 0 3 1 2 2 3 2 0 2 1 3 2 1 3 3 0 2 0 2 3 0 2 2 0 3 1 0 0 2 2 1 2 2 0 0 0 1
 1 2 3 1 1 0 2 2 0 1 0 2 2 3 3 2 1 0 1 2 2 3 3 0 1 0 3 1 1 2 1 0 0 0 0 0 3
 2 0 3 0 0 0 0 1 3 3 1 0 1 1 1 1 1 2 2 3 3 1 2 0 0 0 2 1 1 3 1 0 2 1 1 3 2
 3 0 0 2 1 3 0 1 2 0 2 3 2 0 1 3 3 0 1 3 2 3 0 3 1 2 3 3 2 1 1 3 3 1 3 3 3
 3 3 0 2 2 2 1 3 0 1 3 2 2 2 1 0 1 0 3 3 1 3 1 0 3 1 2 0 0 3 0 1 2 3 3 3 1
 1 0 1 3 3 0 1 2 2 0 3 3 2 3 2 3 2 0 2 1 1 1 0 0 0 3 2 3 1 0 1 0 1 2 3 0 3
 3 2 1 2 0 0 2 1 3 2 0 1 1 1 0 1 3 2 0 0 3 3 0 3 0 0 2 0 1 2 2 2 3 0 3 2 2
 3 3 3 2 1 1 0 3 1 3 3 0 2 3 2 3 3 3 0 0 2 3 0 0 2 3 2 1 1 2 1 2 1 3 1 2 0
 0 1 0 1 0 1 0 2 2 3 2 1 1 2 1 0 3 1 0 0 3 0 1 0 0 1 3 3 0 2 0 1 1 3 3 1 2
 0 2 0 0 3 3 0 2 2 1 3 1 2 0 1 3 1 0 3 1 0 0 3 2 3 2 0 2 1 0 1 2 3 2 1 1 0
 1 2 2 1 1 1 3 1 2 0 3 2 

C:\Users\Priyam\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [20]:
eval_model(y_test,ypred_knn)

[[145   6   0   0]
 [  4 140   2   0]
 [  0  15 129   4]
 [  0   0  10 145]]
              precision    recall  f1-score   support

           0       0.97      0.96      0.97       151
           1       0.87      0.96      0.91       146
           2       0.91      0.87      0.89       148
           3       0.97      0.94      0.95       155

    accuracy                           0.93       600
   macro avg       0.93      0.93      0.93       600
weighted avg       0.93      0.93      0.93       600



### APPLYING SVM

In [21]:
from sklearn.svm import SVC

In [22]:
svm1 = SVC(kernel='linear',C=10)
svm1.fit(x_train,y_train)

SVC(C=10, kernel='linear')

In [23]:
print('Train score',svm1.score(x_train,y_train))
print('Test score',svm1.score(x_test,y_test))     

Train score 0.9828571428571429
Test score 0.9683333333333334


In [24]:
ypred_svm=svm1.predict(x_test)
print(ypred_svm)

[0 2 1 3 1 1 2 0 3 1 0 1 2 3 3 2 3 3 1 0 0 2 1 2 0 1 3 2 2 0 0 0 3 0 1 1 2
 0 3 0 2 3 2 0 3 2 2 1 3 1 3 1 0 0 1 1 1 3 0 0 1 3 3 1 0 0 3 3 1 2 2 2 0 1
 2 0 1 3 2 2 3 2 1 0 1 3 1 3 3 0 3 3 2 1 3 2 2 3 1 1 0 0 1 0 1 3 2 0 1 1 0
 0 3 1 3 2 3 2 0 2 1 3 2 1 3 3 0 2 0 2 3 0 2 2 0 3 1 0 0 2 2 1 2 2 0 0 0 1
 1 2 3 1 1 0 2 2 0 1 0 2 2 3 3 3 1 0 1 2 2 3 3 0 1 0 3 1 1 2 1 0 0 0 0 0 3
 2 0 3 0 0 0 0 1 3 3 1 0 1 1 1 1 2 2 3 3 3 1 2 0 0 0 2 1 1 3 1 1 2 1 1 3 2
 3 0 0 2 1 3 0 1 2 0 2 3 2 0 1 3 3 0 1 3 3 3 0 3 1 2 3 3 2 1 0 3 3 1 3 3 3
 3 3 0 1 2 2 1 3 0 2 3 2 2 2 1 0 1 0 2 3 1 3 1 1 3 1 2 0 0 3 0 1 2 3 3 3 1
 1 0 1 3 3 0 1 2 2 0 3 3 2 3 2 3 2 0 2 1 1 1 0 0 0 3 3 3 1 0 1 0 1 2 3 0 3
 3 2 1 3 0 0 2 1 3 2 0 1 1 1 1 1 3 2 0 0 3 3 0 3 0 0 2 0 1 2 2 2 3 0 3 2 3
 3 3 3 2 1 1 0 3 1 3 3 0 2 3 2 3 3 3 0 0 2 3 0 0 2 3 2 1 1 2 1 3 0 3 1 2 0
 0 1 0 1 0 1 0 2 2 3 2 1 1 2 1 1 3 1 0 0 3 0 1 0 0 2 2 3 0 2 0 1 1 3 3 1 2
 0 2 0 0 3 3 0 2 2 2 3 1 2 0 1 3 1 0 3 1 0 0 3 2 3 2 0 2 1 0 1 2 3 2 1 1 0
 1 2 2 1 0 1 3 1 2 0 2 2 

In [25]:
eval_model(y_test,ypred_svm)

[[146   5   0   0]
 [  1 145   0   0]
 [  0   5 139   4]
 [  0   0   4 151]]
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       151
           1       0.94      0.99      0.96       146
           2       0.97      0.94      0.96       148
           3       0.97      0.97      0.97       155

    accuracy                           0.97       600
   macro avg       0.97      0.97      0.97       600
weighted avg       0.97      0.97      0.97       600



In [26]:
svm2 = SVC(kernel='rbf')
svm2.fit(x_train,y_train)

SVC()

In [27]:
print('Train score',svm2.score(x_train,y_train))
print('Test score',svm2.score(x_test,y_test))     

Train score 0.955
Test score 0.9533333333333334


In [28]:
ypred_svm2=svm2.predict(x_test)
print(ypred_svm2)

[0 2 1 3 1 1 2 0 3 1 0 0 2 3 2 2 3 3 1 0 0 1 1 2 0 1 3 2 2 0 0 0 3 0 1 1 2
 0 3 0 2 3 2 0 2 2 2 1 3 1 3 1 0 0 1 1 1 3 0 0 1 3 3 1 0 0 3 3 1 2 2 2 0 1
 2 0 1 3 2 2 3 2 1 0 1 3 1 3 3 0 3 3 2 1 3 2 2 3 1 1 0 0 1 0 0 3 2 0 1 1 0
 0 3 1 3 2 3 2 0 2 1 3 2 1 3 3 0 3 0 2 3 0 2 2 0 3 1 0 0 2 2 1 2 2 0 0 0 1
 1 2 3 1 1 0 2 2 0 1 0 2 2 3 3 2 1 0 1 2 2 3 3 0 1 0 3 1 1 2 1 0 0 0 0 0 3
 2 0 3 0 0 0 0 1 3 3 1 0 1 1 1 1 2 2 3 3 3 1 2 0 0 0 2 1 1 3 1 0 2 1 1 3 2
 3 0 0 2 1 3 0 1 2 0 2 3 2 0 1 3 3 0 1 3 3 3 0 3 1 2 3 3 2 1 1 3 3 1 3 3 3
 3 3 0 1 2 2 2 3 0 2 3 2 2 2 1 0 1 0 3 3 1 3 1 0 3 1 2 0 0 3 0 1 2 3 3 3 1
 1 0 1 3 3 0 1 1 2 0 3 3 2 3 2 3 2 0 2 1 1 1 0 0 0 2 2 3 1 0 1 0 1 2 3 0 3
 3 2 1 3 0 0 2 1 3 2 0 1 1 1 1 1 3 2 0 0 3 3 0 3 0 0 2 0 1 2 2 2 3 0 3 2 2
 3 3 3 2 1 2 0 3 1 3 3 0 2 3 2 3 3 3 0 0 2 3 0 0 2 3 2 1 1 2 1 3 1 3 1 2 0
 0 1 0 1 0 1 0 2 2 3 2 1 1 2 1 1 3 1 0 0 3 0 1 0 0 1 3 3 0 2 0 1 1 3 3 0 2
 0 2 0 0 3 3 0 2 2 2 3 1 2 0 1 3 1 0 3 1 0 0 3 2 3 2 0 3 1 0 1 2 3 2 1 1 0
 1 2 2 1 1 1 3 1 2 0 2 2 

In [29]:
eval_model(y_test,ypred_svm2)

[[146   5   0   0]
 [  1 144   1   0]
 [  0   9 134   5]
 [  0   0   7 148]]
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       151
           1       0.91      0.99      0.95       146
           2       0.94      0.91      0.92       148
           3       0.97      0.95      0.96       155

    accuracy                           0.95       600
   macro avg       0.95      0.95      0.95       600
weighted avg       0.95      0.95      0.95       600



### APPLYING DECISION TREE

In [30]:
from sklearn.tree import DecisionTreeClassifier

In [31]:
dc=DecisionTreeClassifier(criterion='gini',max_depth=5,min_samples_split=12)
dc.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=5, min_samples_split=12)

In [32]:
print('Train score',dc.score(x_train,y_train))
print('Test score',dc.score(x_test,y_test))     

Train score 0.8785714285714286
Test score 0.7833333333333333


In [33]:
ypred_dc=dc.predict(x_test)
print(ypred_dc)

[0 2 1 3 1 2 2 0 2 2 0 1 2 3 2 2 3 3 1 0 0 1 1 1 0 2 2 2 2 0 1 0 3 0 1 1 3
 0 3 0 2 3 2 0 2 2 1 1 3 1 3 1 0 0 0 0 1 2 0 0 1 3 3 2 0 0 3 3 1 2 2 2 0 1
 3 0 0 3 2 2 3 2 1 0 2 3 2 3 3 0 2 3 2 1 3 2 2 3 2 1 0 0 1 1 0 3 2 0 1 1 0
 0 2 2 2 2 2 3 0 2 1 3 2 1 3 3 0 3 0 1 3 0 2 2 0 2 1 1 0 2 3 1 2 3 0 0 0 1
 2 2 3 1 1 0 2 2 0 2 0 2 2 3 3 3 1 0 1 2 2 3 3 1 1 0 3 1 1 2 1 0 0 0 0 0 3
 2 0 3 0 0 0 0 1 3 2 2 0 1 2 1 1 1 2 2 3 3 1 2 0 0 0 2 1 1 3 1 0 2 2 1 3 2
 2 0 0 2 1 2 0 0 1 0 2 3 2 1 0 3 3 0 2 3 3 3 0 2 1 2 3 3 2 1 1 3 3 0 3 3 3
 3 3 0 2 2 2 2 2 0 2 3 2 2 2 0 0 2 0 2 3 1 3 1 0 3 1 2 0 0 2 0 2 2 3 3 3 0
 1 0 1 3 3 0 1 2 2 0 3 3 2 3 2 3 2 0 2 1 2 1 0 0 0 3 2 3 2 0 1 0 1 3 3 1 2
 2 2 1 2 0 0 3 1 3 2 0 2 1 2 0 2 3 1 0 0 2 3 0 3 0 0 2 0 0 2 2 2 3 1 3 2 2
 3 3 3 2 1 2 0 3 2 3 3 0 2 3 2 3 3 3 0 0 2 3 0 0 2 3 1 2 1 2 1 3 1 3 1 2 0
 0 1 0 1 0 2 0 1 2 3 2 1 1 3 2 0 3 1 0 0 3 0 2 1 0 1 3 3 0 2 0 1 1 3 3 0 3
 1 2 0 0 3 3 0 2 1 1 3 1 2 0 1 3 1 0 2 2 0 0 3 2 3 2 0 3 0 0 1 2 3 2 1 0 0
 0 2 2 1 1 1 3 1 2 1 3 3 

In [34]:
eval_model(y_test,ypred_dc)

[[136  15   0   0]
 [ 16  99  31   0]
 [  0  17 111  20]
 [  0   0  31 124]]
              precision    recall  f1-score   support

           0       0.89      0.90      0.90       151
           1       0.76      0.68      0.71       146
           2       0.64      0.75      0.69       148
           3       0.86      0.80      0.83       155

    accuracy                           0.78       600
   macro avg       0.79      0.78      0.78       600
weighted avg       0.79      0.78      0.78       600



In [35]:
dce=DecisionTreeClassifier(criterion='entropy',max_depth=5,min_samples_split=12)
dce.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5, min_samples_split=12)

In [36]:
print('Train score',dce.score(x_train,y_train))
print('Test score',dce.score(x_test,y_test))     

Train score 0.8878571428571429
Test score 0.8083333333333333


In [37]:
ypred_dce=dce.predict(x_test)
print(ypred_dce)

[0 1 1 3 1 1 2 0 3 1 0 1 2 3 2 2 3 3 1 0 0 1 1 2 0 1 2 2 2 0 0 0 3 0 1 1 2
 0 3 0 1 3 2 0 3 2 2 1 3 1 3 1 0 0 0 0 1 2 0 0 1 3 3 1 0 0 3 3 1 2 1 3 0 1
 2 0 0 3 2 1 3 2 1 0 1 3 2 3 3 0 2 3 1 1 3 2 2 3 1 1 0 0 0 0 0 3 2 0 1 1 0
 0 2 1 2 2 2 3 0 2 1 3 2 1 3 3 0 3 0 2 3 0 2 2 0 3 1 0 0 2 3 0 3 2 0 0 0 1
 2 3 3 1 1 0 2 2 0 1 0 1 2 3 2 3 2 0 0 2 2 2 3 1 0 0 3 1 1 2 1 0 0 0 0 0 3
 2 0 3 0 1 0 0 1 3 3 1 0 0 1 1 1 2 2 2 3 3 1 3 0 0 0 2 1 1 3 1 0 2 1 1 3 1
 3 0 1 1 1 3 0 1 1 0 1 3 2 1 0 3 3 0 1 3 3 3 0 3 1 2 3 3 2 1 1 3 3 1 3 3 3
 3 3 1 1 2 3 1 3 0 1 3 2 2 2 0 0 2 0 2 3 1 3 1 0 3 2 2 0 0 3 0 1 2 3 3 3 1
 0 0 1 3 3 0 1 2 2 0 3 3 2 3 1 3 2 0 2 1 1 1 0 0 1 2 2 3 1 0 1 0 2 3 3 1 3
 3 2 2 3 0 0 3 0 3 2 0 1 1 2 0 1 3 1 0 0 3 3 0 3 0 0 2 0 0 2 2 2 3 0 3 2 2
 3 3 3 2 1 1 0 3 1 3 3 0 2 3 1 3 3 3 1 0 2 3 0 0 2 3 1 1 1 2 1 3 1 3 1 2 0
 0 1 0 1 0 1 1 2 2 3 2 1 1 2 1 0 3 1 0 1 3 0 1 0 1 2 3 3 0 2 1 1 1 3 3 0 3
 0 2 0 0 3 3 0 2 2 2 3 1 2 0 1 3 1 0 3 2 0 0 3 2 3 2 0 3 0 0 1 2 3 2 1 1 1
 0 2 1 1 1 1 3 1 2 0 3 2 

In [38]:
eval_model(y_test,ypred_dce)

[[131  20   0   0]
 [ 21 117   8   0]
 [  0  27  99  22]
 [  0   0  17 138]]
              precision    recall  f1-score   support

           0       0.86      0.87      0.86       151
           1       0.71      0.80      0.75       146
           2       0.80      0.67      0.73       148
           3       0.86      0.89      0.88       155

    accuracy                           0.81       600
   macro avg       0.81      0.81      0.81       600
weighted avg       0.81      0.81      0.81       600



### APPLYING RANDOM FOREST

In [39]:
from sklearn.ensemble import RandomForestClassifier

In [40]:
rf=RandomForestClassifier(n_estimators=200,criterion='entropy', max_depth=8, random_state=42)
rf.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=8, n_estimators=200,
                       random_state=42)

In [41]:
print('Train score',rf.score(x_train,y_train))
print('Test score',rf.score(x_test,y_test))     

Train score 0.995
Test score 0.875


In [42]:
ypred_rf=rf.predict(x_test)
print(ypred_rf)

[0 2 1 3 1 2 2 0 3 1 0 1 2 3 3 2 3 3 1 0 0 1 1 2 0 1 2 2 2 0 0 0 3 0 1 1 2
 0 3 0 2 3 2 0 3 3 2 1 3 1 3 1 0 0 1 0 1 3 0 0 0 3 3 2 0 0 3 3 1 2 2 2 0 1
 2 0 0 3 2 2 3 2 1 0 1 3 2 3 3 0 3 3 2 1 3 2 2 3 2 1 0 0 1 0 0 3 2 0 1 1 0
 0 3 1 2 2 3 3 0 2 1 3 3 1 3 3 0 3 0 2 3 0 2 2 0 3 1 0 0 2 3 0 2 3 0 0 0 1
 2 2 3 1 1 0 2 2 0 1 0 1 2 3 3 2 1 0 0 2 2 3 3 1 0 0 3 1 2 2 1 0 0 0 0 0 3
 2 0 3 0 0 0 0 1 3 3 1 0 1 2 1 1 2 2 3 3 3 1 2 0 0 0 2 1 1 3 1 0 2 1 1 3 1
 3 0 0 2 1 3 0 0 2 0 1 3 2 0 1 3 3 0 2 3 3 3 0 3 1 2 3 3 2 1 1 3 3 1 3 3 3
 3 3 0 1 2 2 2 2 0 2 3 2 3 2 1 0 2 0 3 3 1 3 1 0 3 1 2 0 0 3 0 1 2 3 3 3 1
 0 0 1 3 3 0 1 2 2 0 3 3 2 3 1 3 2 0 2 1 2 1 0 0 1 3 3 3 1 0 1 0 2 2 2 0 3
 3 2 1 3 0 0 3 1 3 2 0 1 1 2 1 1 3 1 0 0 3 3 0 3 0 0 1 0 0 2 2 2 3 0 3 2 2
 3 3 3 2 1 2 0 3 2 3 3 0 2 3 2 3 3 3 0 0 2 3 0 0 2 3 1 1 1 2 1 2 1 3 1 2 0
 0 1 0 1 0 2 0 1 2 3 2 1 1 3 1 0 3 1 0 0 3 0 1 0 0 1 3 3 0 2 1 1 1 3 3 1 2
 0 2 0 0 3 3 0 2 2 1 3 1 1 0 1 3 1 0 3 1 0 0 3 2 3 2 0 3 1 0 1 2 3 2 1 1 0
 1 2 2 1 1 1 3 1 2 0 3 2 

In [43]:
eval_model(y_test,ypred_rf)

[[144   7   0   0]
 [ 10 120  16   0]
 [  0  20 114  14]
 [  0   0   8 147]]
              precision    recall  f1-score   support

           0       0.94      0.95      0.94       151
           1       0.82      0.82      0.82       146
           2       0.83      0.77      0.80       148
           3       0.91      0.95      0.93       155

    accuracy                           0.88       600
   macro avg       0.87      0.87      0.87       600
weighted avg       0.87      0.88      0.87       600



## BEST MODEL WITH ACCURACY IS SVM MODEL WITH LINEAR KERNEL

In [45]:
print(ypred_svm) ### PRICE RANGE FOR SVM MODEL TEST DATA

[0 2 1 3 1 1 2 0 3 1 0 1 2 3 3 2 3 3 1 0 0 2 1 2 0 1 3 2 2 0 0 0 3 0 1 1 2
 0 3 0 2 3 2 0 3 2 2 1 3 1 3 1 0 0 1 1 1 3 0 0 1 3 3 1 0 0 3 3 1 2 2 2 0 1
 2 0 1 3 2 2 3 2 1 0 1 3 1 3 3 0 3 3 2 1 3 2 2 3 1 1 0 0 1 0 1 3 2 0 1 1 0
 0 3 1 3 2 3 2 0 2 1 3 2 1 3 3 0 2 0 2 3 0 2 2 0 3 1 0 0 2 2 1 2 2 0 0 0 1
 1 2 3 1 1 0 2 2 0 1 0 2 2 3 3 3 1 0 1 2 2 3 3 0 1 0 3 1 1 2 1 0 0 0 0 0 3
 2 0 3 0 0 0 0 1 3 3 1 0 1 1 1 1 2 2 3 3 3 1 2 0 0 0 2 1 1 3 1 1 2 1 1 3 2
 3 0 0 2 1 3 0 1 2 0 2 3 2 0 1 3 3 0 1 3 3 3 0 3 1 2 3 3 2 1 0 3 3 1 3 3 3
 3 3 0 1 2 2 1 3 0 2 3 2 2 2 1 0 1 0 2 3 1 3 1 1 3 1 2 0 0 3 0 1 2 3 3 3 1
 1 0 1 3 3 0 1 2 2 0 3 3 2 3 2 3 2 0 2 1 1 1 0 0 0 3 3 3 1 0 1 0 1 2 3 0 3
 3 2 1 3 0 0 2 1 3 2 0 1 1 1 1 1 3 2 0 0 3 3 0 3 0 0 2 0 1 2 2 2 3 0 3 2 3
 3 3 3 2 1 1 0 3 1 3 3 0 2 3 2 3 3 3 0 0 2 3 0 0 2 3 2 1 1 2 1 3 0 3 1 2 0
 0 1 0 1 0 1 0 2 2 3 2 1 1 2 1 1 3 1 0 0 3 0 1 0 0 2 2 3 0 2 0 1 1 3 3 1 2
 0 2 0 0 3 3 0 2 2 2 3 1 2 0 1 3 1 0 3 1 0 0 3 2 3 2 0 2 1 0 1 2 3 2 1 1 0
 1 2 2 1 0 1 3 1 2 0 2 2 